services:
  app:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: apps/${APP_NAME}/Dockerfile
      args:
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: 1
      BLUESKY_HTTPSERVER_URL: ${BLUESKY_HTTPSERVER_URL}
      PVWS_URL: ${PVWS_URL}
    restart: unless-stopped
    expose:
      - "3000"
    # ports:
    #   - 3000:3000
