services:
  app:
    container_name: ${APP_NAME}
    image: ghcr.io/cnpem/sophys-web__${APP_NAME}:${APP_VERSION}
    environment:
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: 1
      BLUESKY_HTTPSERVER_URL: ${BLUESKY_HTTPSERVER_URL}
      NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
      NEXT_PUBLIC_PVWS_URL: ${NEXT_PUBLIC_PVWS_URL}
    restart: unless-stopped
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`localhost`) && PathPrefix(`/${APP_NAME}`)"
      - "traefik.http.middlewares.${APP_NAME}.stripprefix.prefixes=`${NEXT_PUBLIC_BASE_PATH}`"
      - "traefik.http.routers.${APP_NAME}.entrypoints=web"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000"
    networks:
      - ${TRAEFIK_NETWORK}

networks:
  ${TRAEFIK_NETWORK}:
    external: true
