packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  # Next.js
  next: "^15.3.6"
  # Tanstack & tRPC
  "@tanstack/react-query": ^5.69.0
  "@trpc/client": ^11.0.0
  "@trpc/react-query": ^11.0.0
  "@trpc/tanstack-react-query": ^11.0.0
  "@trpc/server": ^11.0.0
  "@tanstack/react-query-devtools": "^5.69.0"

  # dev tools
  eslint: ^9.23.0
  prettier: ^3.5.3
  tailwindcss: ^4.1.0
  typescript: ^5.8.3

  # misc
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    react: 19.1.2
    react-dom: 19.1.2
    "@types/react": ^19.1.2
    "@types/react-dom": ^19.1.2
