/**
 * Generated by orval v8.6.2 for tiled v0.2.10b8 openapi spec.
 * Edited manually to keed only the endpoints of interest for the tiled-client package.
 */
import * as zod from "zod";

/**
 * @summary Healthz
 */
export const HealthzHealthzGetResponse = zod.unknown();

/**
 * @summary Ui
 */
export const UiUiPathGetParams = zod.object({
  path: zod.unknown(),
});

export const UiUiPathGetResponse = zod.unknown();

/**
 * @summary Tiled Ui Settings
 */
export const TiledUiSettingsTiledUiSettingsGetResponse = zod.unknown();

/**
 * @summary About
 */
export const AboutApiV1GetResponse = zod.object({
  api_version: zod.number(),
  library_version: zod.string(),
  formats: zod.record(zod.string(), zod.array(zod.string())),
  aliases: zod.record(
    zod.string(),
    zod.record(zod.string(), zod.array(zod.string())),
  ),
  queries: zod.array(zod.string()),
  authentication: zod.object({
    required: zod.boolean(),
    providers: zod.array(
      zod.object({
        provider: zod.string(),
        mode: zod.enum(["internal", "external", "password"]),
        links: zod.record(zod.string(), zod.string()),
        confirmation_message: zod.union([zod.string(), zod.null()]).optional(),
        extra_scopes: zod
          .union([zod.array(zod.string()), zod.null()])
          .optional(),
      }),
    ),
    links: zod
      .union([
        zod.object({
          whoami: zod.string(),
          apikey: zod.string(),
          refresh_session: zod.string(),
          revoke_session: zod.string(),
          logout: zod.string(),
        }),
        zod.null(),
      ])
      .optional(),
  }),
  links: zod.record(zod.string(), zod.string()),
  meta: zod.record(zod.string(), zod.unknown()),
});

/**
 * Fetch the metadata and structure information for one entry
 * @summary Metadata
 */
export const MetadataApiV1MetadataPathGetParams = zod.object({
  path: zod.string(),
});

export const metadataApiV1MetadataPathGetQueryFieldsDefault = [
  `metadata`,
  `structure_family`,
  `structure`,
  `count`,
  `sorting`,
  `specs`,
  `data_sources`,
  ``,
  `access_blob`,
];
export const metadataApiV1MetadataPathGetQueryMaxDepthOneMin = 0;
export const metadataApiV1MetadataPathGetQueryMaxDepthOneMax = 5;

export const metadataApiV1MetadataPathGetQueryOmitLinksDefault = false;
export const metadataApiV1MetadataPathGetQueryIncludeDataSourcesDefault = false;
export const metadataApiV1MetadataPathGetQueryRootPathDefault = false;

export const MetadataApiV1MetadataPathGetQueryParams = zod.object({
  fields: zod.union([
    zod.array(
      zod.enum([
        "metadata",
        "structure_family",
        "structure",
        "count",
        "sorting",
        "specs",
        "data_sources",
        "",
        "access_blob",
      ]),
    ),
    zod.null(),
  ]),
  select_metadata: zod.union([zod.string(), zod.null()]).optional(),
  max_depth: zod
    .union([
      zod
        .number()
        .min(metadataApiV1MetadataPathGetQueryMaxDepthOneMin)
        .max(metadataApiV1MetadataPathGetQueryMaxDepthOneMax),
      zod.null(),
    ])
    .optional(),
  omit_links: zod
    .boolean()
    .default(metadataApiV1MetadataPathGetQueryOmitLinksDefault),
  include_data_sources: zod
    .boolean()
    .default(metadataApiV1MetadataPathGetQueryIncludeDataSourcesDefault),
  root_path: zod
    .boolean()
    .default(metadataApiV1MetadataPathGetQueryRootPathDefault),
});

export const metadataApiV1MetadataPathGetResponseDataOneAttributesSpecsOneItemNameMax = 255;

export const metadataApiV1MetadataPathGetResponseDataOneAttributesSpecsOneItemVersionOneMax = 255;

export const metadataApiV1MetadataPathGetResponseDataOneAttributesSpecsOneMax = 20;

export const metadataApiV1MetadataPathGetResponseDataOneAttributesStructureOneResizableDefault =
  false;
export const metadataApiV1MetadataPathGetResponseDataOneAttributesStructureThreeResizableDefault =
  false;
export const metadataApiV1MetadataPathGetResponseDataOneAttributesStructureFourResizableDefault =
  false;
export const metadataApiV1MetadataPathGetResponseDataOneAttributesStructureFourLayoutDefault = `COO`;
export const metadataApiV1MetadataPathGetResponseDataOneAttributesStructureSixResizableDefault =
  false;
export const metadataApiV1MetadataPathGetResponseDataOneAttributesDataSourcesOneItemParametersDefault =
  {};
export const metadataApiV1MetadataPathGetResponseDataOneAttributesDataSourcesOneItemPropertiesDefault =
  {};
export const metadataApiV1MetadataPathGetResponseDataOneAttributesDataSourcesOneItemAssetsDefault =
  [];
export const metadataApiV1MetadataPathGetResponseDataOneAttributesDataSourcesOneItemManagementDefault = `writable`;

export const MetadataApiV1MetadataPathGetResponse = zod.object({
  data: zod.union([
    zod.object({
      id: zod.union([zod.string(), zod.string().uuid()]),
      attributes: zod.object({
        ancestors: zod.array(zod.string()),
        structure_family: zod
          .union([
            zod.enum([
              "array",
              "awkward",
              "container",
              "ragged",
              "sparse",
              "table",
            ]),
            zod.null(),
          ])
          .optional(),
        specs: zod
          .union([
            zod
              .array(
                zod.object({
                  name: zod
                    .string()
                    .max(
                      metadataApiV1MetadataPathGetResponseDataOneAttributesSpecsOneItemNameMax,
                    ),
                  version: zod
                    .union([
                      zod
                        .string()
                        .max(
                          metadataApiV1MetadataPathGetResponseDataOneAttributesSpecsOneItemVersionOneMax,
                        ),
                      zod.null(),
                    ])
                    .optional(),
                }),
              )
              .max(
                metadataApiV1MetadataPathGetResponseDataOneAttributesSpecsOneMax,
              ),
            zod.null(),
          ])
          .optional(),
        metadata: zod
          .union([zod.record(zod.string(), zod.unknown()), zod.null()])
          .optional(),
        structure: zod
          .union([
            zod.object({
              data_type: zod.union([
                zod.object({
                  endianness: zod
                    .enum(["big", "little", "not_applicable"])
                    .describe(
                      "An enum of endian values: big, little, not_applicable.",
                    ),
                  kind: zod
                    .enum([
                      "t",
                      "b",
                      "i",
                      "u",
                      "f",
                      "c",
                      "m",
                      "M",
                      "S",
                      "U",
                      "V",
                    ])
                    .describe(
                      'See https:\/\/numpy.org\/devdocs\/reference\/arrays.interface.html#object.__array_interface__\n\nThe term \"kind\" comes from the numpy API as well.\n\nNote: At import time, the environment variable ``TILED_ALLOW_OBJECT_ARRAYS``\nis checked. If it is set to anything other than ``\"0\"``, then this\nEnum gets an additional member::\n\n    object = \"O\"\n\nto support numpy \'object\'-type arrays which hold generic Python objects.\nNumpy \'object\'-type arrays are not enabled by default because their binary\nrepresentation is not interpretable by clients other than Python.  It is\nrecommended to convert your data to a non-object type if possible so that it\ncan be read by non-Python clients.',
                    ),
                  itemsize: zod.number(),
                  dt_units: zod.union([zod.string(), zod.null()]).optional(),
                }),
                zod.object({
                  itemsize: zod.number(),
                  fields: zod.array(
                    zod.object({
                      name: zod.string(),
                      dtype: zod.union([
                        zod.object({
                          endianness: zod
                            .enum(["big", "little", "not_applicable"])
                            .describe(
                              "An enum of endian values: big, little, not_applicable.",
                            ),
                          kind: zod
                            .enum([
                              "t",
                              "b",
                              "i",
                              "u",
                              "f",
                              "c",
                              "m",
                              "M",
                              "S",
                              "U",
                              "V",
                            ])
                            .describe(
                              'See https:\/\/numpy.org\/devdocs\/reference\/arrays.interface.html#object.__array_interface__\n\nThe term \"kind\" comes from the numpy API as well.\n\nNote: At import time, the environment variable ``TILED_ALLOW_OBJECT_ARRAYS``\nis checked. If it is set to anything other than ``\"0\"``, then this\nEnum gets an additional member::\n\n    object = \"O\"\n\nto support numpy \'object\'-type arrays which hold generic Python objects.\nNumpy \'object\'-type arrays are not enabled by default because their binary\nrepresentation is not interpretable by clients other than Python.  It is\nrecommended to convert your data to a non-object type if possible so that it\ncan be read by non-Python clients.',
                            ),
                          itemsize: zod.number(),
                          dt_units: zod
                            .union([zod.string(), zod.null()])
                            .optional(),
                        }),
                        zod.unknown(),
                      ]),
                      shape: zod.union([zod.array(zod.number()), zod.null()]),
                    }),
                  ),
                }),
              ]),
              chunks: zod.array(zod.array(zod.number())),
              shape: zod.array(zod.number()),
              dims: zod.union([zod.array(zod.string()), zod.null()]).optional(),
              resizable: zod
                .union([zod.boolean(), zod.array(zod.boolean())])
                .default(
                  metadataApiV1MetadataPathGetResponseDataOneAttributesStructureOneResizableDefault,
                ),
            }),
            zod.object({
              length: zod.number(),
              form: zod.record(zod.string(), zod.unknown()),
            }),
            zod
              .object({
                data_type: zod.union([
                  zod.object({
                    endianness: zod
                      .enum(["big", "little", "not_applicable"])
                      .describe(
                        "An enum of endian values: big, little, not_applicable.",
                      ),
                    kind: zod
                      .enum([
                        "t",
                        "b",
                        "i",
                        "u",
                        "f",
                        "c",
                        "m",
                        "M",
                        "S",
                        "U",
                        "V",
                      ])
                      .describe(
                        'See https:\/\/numpy.org\/devdocs\/reference\/arrays.interface.html#object.__array_interface__\n\nThe term \"kind\" comes from the numpy API as well.\n\nNote: At import time, the environment variable ``TILED_ALLOW_OBJECT_ARRAYS``\nis checked. If it is set to anything other than ``\"0\"``, then this\nEnum gets an additional member::\n\n    object = \"O\"\n\nto support numpy \'object\'-type arrays which hold generic Python objects.\nNumpy \'object\'-type arrays are not enabled by default because their binary\nrepresentation is not interpretable by clients other than Python.  It is\nrecommended to convert your data to a non-object type if possible so that it\ncan be read by non-Python clients.',
                      ),
                    itemsize: zod.number(),
                    dt_units: zod.union([zod.string(), zod.null()]).optional(),
                  }),
                  zod.object({
                    itemsize: zod.number(),
                    fields: zod.array(
                      zod.object({
                        name: zod.string(),
                        dtype: zod.union([
                          zod.object({
                            endianness: zod
                              .enum(["big", "little", "not_applicable"])
                              .describe(
                                "An enum of endian values: big, little, not_applicable.",
                              ),
                            kind: zod
                              .enum([
                                "t",
                                "b",
                                "i",
                                "u",
                                "f",
                                "c",
                                "m",
                                "M",
                                "S",
                                "U",
                                "V",
                              ])
                              .describe(
                                'See https:\/\/numpy.org\/devdocs\/reference\/arrays.interface.html#object.__array_interface__\n\nThe term \"kind\" comes from the numpy API as well.\n\nNote: At import time, the environment variable ``TILED_ALLOW_OBJECT_ARRAYS``\nis checked. If it is set to anything other than ``\"0\"``, then this\nEnum gets an additional member::\n\n    object = \"O\"\n\nto support numpy \'object\'-type arrays which hold generic Python objects.\nNumpy \'object\'-type arrays are not enabled by default because their binary\nrepresentation is not interpretable by clients other than Python.  It is\nrecommended to convert your data to a non-object type if possible so that it\ncan be read by non-Python clients.',
                              ),
                            itemsize: zod.number(),
                            dt_units: zod
                              .union([zod.string(), zod.null()])
                              .optional(),
                          }),
                          zod.unknown(),
                        ]),
                        shape: zod.union([zod.array(zod.number()), zod.null()]),
                      }),
                    ),
                  }),
                ]),
                shape: zod.array(zod.union([zod.number(), zod.null()])),
                size: zod.number(),
                chunks: zod.array(
                  zod.union([zod.array(zod.number()), zod.null()]),
                ),
                dims: zod
                  .union([zod.array(zod.string()), zod.null()])
                  .optional(),
                resizable: zod
                  .union([zod.boolean(), zod.array(zod.boolean())])
                  .default(
                    metadataApiV1MetadataPathGetResponseDataOneAttributesStructureThreeResizableDefault,
                  ),
              })
              .describe(
                'A structure representing a ragged array\n\nRagged arrays are arrays with variable-length trailing dimensions (rows). The first\ndimension is always a known integer, while any variable dimensions are represented\nby None in its shape.\n\nParameters\n----------\ndata_type : BuiltinDtype | StructDtype\n    Serializable representation of the array\'s data type.\nshape : tuple[int | None, ...]\n    The shape of the array, where the first dimension is always a known integer,\n    and any variable dimensions are represented by None.\nsize : int\n    The total number of elements in the array.\nchunks : tuple[tuple[int, ...] | None, ...]\n    The dask-like chunks of the array, where the first dimension is always\n    partitioned into known integer chunks, and any variable dimensions are null.\n    From the storage perspective, each chunk represents a row in the underlying table,\n    which may contain information about multiple rows of the ragged array.\ndims : tuple[str, ...] | None, optional\n    Optional tuple of dimension names, e.g. (\"time\", \"x\"), or None for unnamed dimensions.\nresizable : bool | tuple[bool, ...], optional\n    Whether the array is resizable along any dimension.',
              ),
            zod.object({
              chunks: zod.array(zod.array(zod.number())),
              shape: zod.array(zod.number()),
              data_type: zod
                .union([
                  zod.object({
                    endianness: zod
                      .enum(["big", "little", "not_applicable"])
                      .describe(
                        "An enum of endian values: big, little, not_applicable.",
                      ),
                    kind: zod
                      .enum([
                        "t",
                        "b",
                        "i",
                        "u",
                        "f",
                        "c",
                        "m",
                        "M",
                        "S",
                        "U",
                        "V",
                      ])
                      .describe(
                        'See https:\/\/numpy.org\/devdocs\/reference\/arrays.interface.html#object.__array_interface__\n\nThe term \"kind\" comes from the numpy API as well.\n\nNote: At import time, the environment variable ``TILED_ALLOW_OBJECT_ARRAYS``\nis checked. If it is set to anything other than ``\"0\"``, then this\nEnum gets an additional member::\n\n    object = \"O\"\n\nto support numpy \'object\'-type arrays which hold generic Python objects.\nNumpy \'object\'-type arrays are not enabled by default because their binary\nrepresentation is not interpretable by clients other than Python.  It is\nrecommended to convert your data to a non-object type if possible so that it\ncan be read by non-Python clients.',
                      ),
                    itemsize: zod.number(),
                    dt_units: zod.union([zod.string(), zod.null()]).optional(),
                  }),
                  zod.object({
                    itemsize: zod.number(),
                    fields: zod.array(
                      zod.object({
                        name: zod.string(),
                        dtype: zod.union([
                          zod.object({
                            endianness: zod
                              .enum(["big", "little", "not_applicable"])
                              .describe(
                                "An enum of endian values: big, little, not_applicable.",
                              ),
                            kind: zod
                              .enum([
                                "t",
                                "b",
                                "i",
                                "u",
                                "f",
                                "c",
                                "m",
                                "M",
                                "S",
                                "U",
                                "V",
                              ])
                              .describe(
                                'See https:\/\/numpy.org\/devdocs\/reference\/arrays.interface.html#object.__array_interface__\n\nThe term \"kind\" comes from the numpy API as well.\n\nNote: At import time, the environment variable ``TILED_ALLOW_OBJECT_ARRAYS``\nis checked. If it is set to anything other than ``\"0\"``, then this\nEnum gets an additional member::\n\n    object = \"O\"\n\nto support numpy \'object\'-type arrays which hold generic Python objects.\nNumpy \'object\'-type arrays are not enabled by default because their binary\nrepresentation is not interpretable by clients other than Python.  It is\nrecommended to convert your data to a non-object type if possible so that it\ncan be read by non-Python clients.',
                              ),
                            itemsize: zod.number(),
                            dt_units: zod
                              .union([zod.string(), zod.null()])
                              .optional(),
                          }),
                          zod.unknown(),
                        ]),
                        shape: zod.union([zod.array(zod.number()), zod.null()]),
                      }),
                    ),
                  }),
                  zod.null(),
                ])
                .optional(),
              coord_data_type: zod
                .union([
                  zod.object({
                    endianness: zod
                      .enum(["big", "little", "not_applicable"])
                      .describe(
                        "An enum of endian values: big, little, not_applicable.",
                      ),
                    kind: zod
                      .enum([
                        "t",
                        "b",
                        "i",
                        "u",
                        "f",
                        "c",
                        "m",
                        "M",
                        "S",
                        "U",
                        "V",
                      ])
                      .describe(
                        'See https:\/\/numpy.org\/devdocs\/reference\/arrays.interface.html#object.__array_interface__\n\nThe term \"kind\" comes from the numpy API as well.\n\nNote: At import time, the environment variable ``TILED_ALLOW_OBJECT_ARRAYS``\nis checked. If it is set to anything other than ``\"0\"``, then this\nEnum gets an additional member::\n\n    object = \"O\"\n\nto support numpy \'object\'-type arrays which hold generic Python objects.\nNumpy \'object\'-type arrays are not enabled by default because their binary\nrepresentation is not interpretable by clients other than Python.  It is\nrecommended to convert your data to a non-object type if possible so that it\ncan be read by non-Python clients.',
                      ),
                    itemsize: zod.number(),
                    dt_units: zod.union([zod.string(), zod.null()]).optional(),
                  }),
                  zod.null(),
                ])
                .optional(),
              dims: zod.union([zod.array(zod.string()), zod.null()]).optional(),
              resizable: zod
                .union([zod.boolean(), zod.array(zod.boolean())])
                .default(
                  metadataApiV1MetadataPathGetResponseDataOneAttributesStructureFourResizableDefault,
                ),
              layout: zod
                .enum(["COO"])
                .default(
                  metadataApiV1MetadataPathGetResponseDataOneAttributesStructureFourLayoutDefault,
                ),
            }),
            zod.object({
              contents: zod.union([
                zod.record(zod.string(), zod.unknown()),
                zod.null(),
              ]),
              count: zod.number(),
            }),
            zod.object({
              arrow_schema: zod.string(),
              npartitions: zod.number(),
              columns: zod.array(zod.string()),
              resizable: zod
                .union([zod.boolean(), zod.array(zod.boolean())])
                .default(
                  metadataApiV1MetadataPathGetResponseDataOneAttributesStructureSixResizableDefault,
                ),
            }),
            zod.null(),
          ])
          .optional(),
        access_blob: zod
          .union([zod.record(zod.string(), zod.unknown()), zod.null()])
          .optional(),
        sorting: zod
          .union([
            zod.array(
              zod.object({
                key: zod.string(),
                direction: zod.union([zod.literal(1), zod.literal(-1)]),
              }),
            ),
            zod.null(),
          ])
          .optional(),
        data_sources: zod
          .union([
            zod.array(
              zod.object({
                id: zod.union([zod.number(), zod.null()]).optional(),
                structure_family: zod.enum([
                  "array",
                  "awkward",
                  "container",
                  "ragged",
                  "sparse",
                  "table",
                ]),
                structure: zod.union([zod.unknown(), zod.null()]),
                mimetype: zod.union([zod.string(), zod.null()]).optional(),
                parameters: zod
                  .record(zod.string(), zod.unknown())
                  .default(
                    metadataApiV1MetadataPathGetResponseDataOneAttributesDataSourcesOneItemParametersDefault,
                  ),
                properties: zod
                  .record(zod.string(), zod.unknown())
                  .default(
                    metadataApiV1MetadataPathGetResponseDataOneAttributesDataSourcesOneItemPropertiesDefault,
                  ),
                assets: zod
                  .array(
                    zod.object({
                      data_uri: zod.string(),
                      is_directory: zod.boolean(),
                      parameter: zod
                        .union([zod.string(), zod.null()])
                        .optional(),
                      num: zod.union([zod.number(), zod.null()]).optional(),
                      id: zod.union([zod.number(), zod.null()]).optional(),
                    }),
                  )
                  .default(
                    metadataApiV1MetadataPathGetResponseDataOneAttributesDataSourcesOneItemAssetsDefault,
                  ),
                management: zod
                  .enum(["external", "immutable", "locked", "writable"])
                  .default(
                    metadataApiV1MetadataPathGetResponseDataOneAttributesDataSourcesOneItemManagementDefault,
                  ),
              }),
            ),
            zod.null(),
          ])
          .optional(),
      }),
      links: zod
        .union([zod.record(zod.string(), zod.unknown()), zod.null()])
        .optional(),
      meta: zod
        .union([zod.record(zod.string(), zod.unknown()), zod.null()])
        .optional(),
    }),
    zod.null(),
  ]),
  error: zod
    .union([
      zod.object({
        code: zod.number(),
        message: zod.string(),
      }),
      zod.null(),
    ])
    .optional(),
  links: zod
    .union([zod.record(zod.string(), zod.unknown()), zod.null()])
    .optional(),
  meta: zod
    .union([zod.record(zod.string(), zod.unknown()), zod.null()])
    .optional(),
});

/**
 * Fetch a chunk of array-like data.
 * @summary Array Block
 */
export const ArrayBlockApiV1ArrayBlockPathGetParams = zod.object({
  path: zod.string(),
});

export const arrayBlockApiV1ArrayBlockPathGetQueryBlockRegExp = new RegExp(
  "^[0-9]\*(,[0-9]+)\*$",
);
export const arrayBlockApiV1ArrayBlockPathGetQuerySliceDefault = ``;
export const arrayBlockApiV1ArrayBlockPathGetQuerySliceRegExp = new RegExp(
  "^(?:(?:-?\\d+)?:){0,2}(?:-?\\d+)?(?:,(?:(?:-?\\d+)?:){0,2}(?:-?\\d+)?)\*$",
);

export const arrayBlockApiV1ArrayBlockPathGetQueryExpectedShapeOneRegExp =
  new RegExp("^[0-9]+(,[0-9]+)\*$|^scalar$");

export const ArrayBlockApiV1ArrayBlockPathGetQueryParams = zod.object({
  format: zod.union([zod.string(), zod.null()]).optional(),
  filename: zod.union([zod.string(), zod.null()]).optional(),
  block: zod.string().regex(arrayBlockApiV1ArrayBlockPathGetQueryBlockRegExp),
  slice: zod
    .string()
    .regex(arrayBlockApiV1ArrayBlockPathGetQuerySliceRegExp)
    .default(arrayBlockApiV1ArrayBlockPathGetQuerySliceDefault),
  expected_shape: zod
    .union([
      zod
        .string()
        .min(1)
        .regex(arrayBlockApiV1ArrayBlockPathGetQueryExpectedShapeOneRegExp),
      zod.null(),
    ])
    .optional(),
});

export const ArrayBlockApiV1ArrayBlockPathGetResponse = zod.object({
  data: zod.union([zod.unknown(), zod.null()]),
  error: zod
    .union([
      zod.object({
        code: zod.number(),
        message: zod.string(),
      }),
      zod.null(),
    ])
    .optional(),
  links: zod.union([zod.unknown(), zod.null()]).optional(),
  meta: zod.union([zod.unknown(), zod.null()]).optional(),
});

/**
 * Fetch a slice of array-like data.
 * @summary Full Array
 */
export const FullArrayApiV1ArrayFullPathGetParams = zod.object({
  path: zod.string(),
});

export const fullArrayApiV1ArrayFullPathGetQuerySliceDefault = ``;
export const fullArrayApiV1ArrayFullPathGetQuerySliceRegExp = new RegExp(
  "^(?:(?:-?\\d+)?:){0,2}(?:-?\\d+)?(?:,(?:(?:-?\\d+)?:){0,2}(?:-?\\d+)?)\*$",
);

export const fullArrayApiV1ArrayFullPathGetQueryExpectedShapeOneRegExp =
  new RegExp("^[0-9]+(,[0-9]+)\*$|^scalar$");

export const FullArrayApiV1ArrayFullPathGetQueryParams = zod.object({
  format: zod.union([zod.string(), zod.null()]).optional(),
  filename: zod.union([zod.string(), zod.null()]).optional(),
  slice: zod
    .string()
    .regex(fullArrayApiV1ArrayFullPathGetQuerySliceRegExp)
    .default(fullArrayApiV1ArrayFullPathGetQuerySliceDefault),
  expected_shape: zod
    .union([
      zod
        .string()
        .min(1)
        .regex(fullArrayApiV1ArrayFullPathGetQueryExpectedShapeOneRegExp),
      zod.null(),
    ])
    .optional(),
});

export const FullArrayApiV1ArrayFullPathGetResponse = zod.object({
  data: zod.union([zod.unknown(), zod.null()]),
  error: zod
    .union([
      zod.object({
        code: zod.number(),
        message: zod.string(),
      }),
      zod.null(),
    ])
    .optional(),
  links: zod.union([zod.unknown(), zod.null()]).optional(),
  meta: zod.union([zod.unknown(), zod.null()]).optional(),
});

/**
 * @summary Close Stream
 */
export const CloseStreamApiV1StreamClosePathDeleteParams = zod.object({
  path: zod.string(),
});

export const CloseStreamApiV1StreamClosePathDeleteResponse = zod.unknown();

/**
 * @summary Ragged Full
 */
export const RaggedFullApiV1RaggedFullPathGetParams = zod.object({
  path: zod.string(),
});

export const raggedFullApiV1RaggedFullPathGetQuerySliceDefault = ``;
export const raggedFullApiV1RaggedFullPathGetQuerySliceRegExp = new RegExp(
  "^(?:(?:-?\\d+)?:){0,2}(?:-?\\d+)?(?:,(?:(?:-?\\d+)?:){0,2}(?:-?\\d+)?)\*$",
);

export const RaggedFullApiV1RaggedFullPathGetQueryParams = zod.object({
  format: zod.union([zod.string(), zod.null()]).optional(),
  filename: zod.union([zod.string(), zod.null()]).optional(),
  slice: zod
    .string()
    .regex(raggedFullApiV1RaggedFullPathGetQuerySliceRegExp)
    .default(raggedFullApiV1RaggedFullPathGetQuerySliceDefault),
});

export const RaggedFullApiV1RaggedFullPathGetResponse = zod.object({
  data: zod.union([zod.unknown(), zod.null()]),
  error: zod
    .union([
      zod.object({
        code: zod.number(),
        message: zod.string(),
      }),
      zod.null(),
    ])
    .optional(),
  links: zod.union([zod.unknown(), zod.null()]).optional(),
  meta: zod.union([zod.unknown(), zod.null()]).optional(),
});

/**
 * Fetch a partition (continuous block of rows) from a DataFrame [GET route].
 * @summary Table Partition
 */
export const TablePartitionApiV1TablePartitionPathGetParams = zod.object({
  path: zod.string(),
});

export const TablePartitionApiV1TablePartitionPathGetQueryParams = zod.object({
  partition: zod.number(),
  column: zod.union([zod.array(zod.string()).min(1), zod.null()]).optional(),
  field: zod.union([zod.array(zod.string()).min(1), zod.null()]).optional(),
  format: zod.union([zod.string(), zod.null()]).optional(),
  filename: zod.union([zod.string(), zod.null()]).optional(),
});

export const TablePartitionApiV1TablePartitionPathGetResponse = zod.object({
  data: zod.union([zod.unknown(), zod.null()]),
  error: zod
    .union([
      zod.object({
        code: zod.number(),
        message: zod.string(),
      }),
      zod.null(),
    ])
    .optional(),
  links: zod.union([zod.unknown(), zod.null()]).optional(),
  meta: zod.union([zod.unknown(), zod.null()]).optional(),
});

/**
 * Fetch the data for the given table [GET route].
 * @summary Full 'Table' Data
 */
export const FullTableDataApiV1TableFullPathGetParams = zod.object({
  path: zod.string(),
});

export const FullTableDataApiV1TableFullPathGetQueryParams = zod.object({
  column: zod.union([zod.array(zod.string()).min(1), zod.null()]).optional(),
  format: zod.union([zod.string(), zod.null()]).optional(),
  filename: zod.union([zod.string(), zod.null()]).optional(),
});

export const FullTableDataApiV1TableFullPathGetResponse = zod.object({
  data: zod.union([zod.unknown(), zod.null()]),
  error: zod
    .union([
      zod.object({
        code: zod.number(),
        message: zod.string(),
      }),
      zod.null(),
    ])
    .optional(),
  links: zod.union([zod.unknown(), zod.null()]).optional(),
  meta: zod.union([zod.unknown(), zod.null()]).optional(),
});

/**
 * Fetch the data for the given container via a GET request.
 * @summary Full 'Container' Metadata And Data
 */
export const FullContainerMetadataAndDataApiV1ContainerFullPathGetParams =
  zod.object({
    path: zod.string(),
  });

export const FullContainerMetadataAndDataApiV1ContainerFullPathGetQueryParams =
  zod.object({
    field: zod.union([zod.array(zod.string()).min(1), zod.null()]).optional(),
    format: zod.union([zod.string(), zod.null()]).optional(),
    filename: zod.union([zod.string(), zod.null()]).optional(),
  });

export const FullContainerMetadataAndDataApiV1ContainerFullPathGetResponse =
  zod.object({
    data: zod.union([zod.unknown(), zod.null()]),
    error: zod
      .union([
        zod.object({
          code: zod.number(),
          message: zod.string(),
        }),
        zod.null(),
      ])
      .optional(),
    links: zod.union([zod.unknown(), zod.null()]).optional(),
    meta: zod.union([zod.unknown(), zod.null()]).optional(),
  });

/**
 * Fetch a slice of AwkwardArray data.

Note that there is a POST route on this same path with equivalent functionality.
HTTP caches tends to engage with GET but not POST, so that GET route may be
preferred for that reason. However, HTTP clients, servers, and proxies
typically impose a length limit on URLs. (The HTTP spec does not specify
one, but this is a pragmatic measure.) For requests with large numbers of
form_key parameters, POST may be the only option.
 * @summary Awkwardarray Buffers
 */
export const AwkwardArrayBuffersApiV1AwkwardBuffersPathGetParams = zod.object({
  path: zod.string(),
});

export const AwkwardArrayBuffersApiV1AwkwardBuffersPathGetQueryParams =
  zod.object({
    form_key: zod
      .union([zod.array(zod.string()).min(1), zod.null()])
      .optional(),
    format: zod.union([zod.string(), zod.null()]).optional(),
    filename: zod.union([zod.string(), zod.null()]).optional(),
  });

export const AwkwardArrayBuffersApiV1AwkwardBuffersPathGetResponse = zod.object(
  {
    data: zod.union([zod.unknown(), zod.null()]),
    error: zod
      .union([
        zod.object({
          code: zod.number(),
          message: zod.string(),
        }),
        zod.null(),
      ])
      .optional(),
    links: zod.union([zod.unknown(), zod.null()]).optional(),
    meta: zod.union([zod.unknown(), zod.null()]).optional(),
  },
);

/**
 * Fetch a slice of AwkwardArray data.
 * @summary Full Awkwardarray
 */
export const FullAwkwardArrayApiV1AwkwardFullPathGetParams = zod.object({
  path: zod.string(),
});

export const FullAwkwardArrayApiV1AwkwardFullPathGetQueryParams = zod.object({
  format: zod.union([zod.string(), zod.null()]).optional(),
  filename: zod.union([zod.string(), zod.null()]).optional(),
});

export const FullAwkwardArrayApiV1AwkwardFullPathGetResponse = zod.object({
  data: zod.union([zod.unknown(), zod.null()]),
  error: zod
    .union([
      zod.object({
        code: zod.number(),
        message: zod.string(),
      }),
      zod.null(),
    ])
    .optional(),
  links: zod.union([zod.unknown(), zod.null()]).optional(),
  meta: zod.union([zod.unknown(), zod.null()]).optional(),
});

/**
 * @summary Get Revisions
 */
export const GetRevisionsApiV1RevisionsPathGetParams = zod.object({
  path: zod.string(),
});

export const getRevisionsApiV1RevisionsPathGetQueryPageOffsetOneMin = 0;

export const getRevisionsApiV1RevisionsPathGetQueryPageCursorOneMin = 0;

export const getRevisionsApiV1RevisionsPathGetQueryPageLimitDefault = 100;
export const getRevisionsApiV1RevisionsPathGetQueryPageLimitMin = 0;
export const getRevisionsApiV1RevisionsPathGetQueryPageLimitMax = 300;

export const GetRevisionsApiV1RevisionsPathGetQueryParams = zod.object({
  "page[offset]": zod
    .union([
      zod.number().min(getRevisionsApiV1RevisionsPathGetQueryPageOffsetOneMin),
      zod.null(),
    ])
    .optional(),
  "page[cursor]": zod
    .union([
      zod.number().min(getRevisionsApiV1RevisionsPathGetQueryPageCursorOneMin),
      zod.null(),
    ])
    .optional(),
  "page[limit]": zod
    .number()
    .min(getRevisionsApiV1RevisionsPathGetQueryPageLimitMin)
    .max(getRevisionsApiV1RevisionsPathGetQueryPageLimitMax)
    .default(getRevisionsApiV1RevisionsPathGetQueryPageLimitDefault),
});

export const GetRevisionsApiV1RevisionsPathGetResponse = zod.unknown();

/**
 * @summary Get Asset
 */
export const GetAssetApiV1AssetBytesPathGetParams = zod.object({
  path: zod.string(),
});

export const GetAssetApiV1AssetBytesPathGetQueryParams = zod.object({
  id: zod.number(),
  relative_path: zod.union([zod.string(), zod.null()]).optional(),
});

export const GetAssetApiV1AssetBytesPathGetResponse = zod.unknown();

/**
 * @summary Get Asset Manifest
 */
export const GetAssetManifestApiV1AssetManifestPathGetParams = zod.object({
  path: zod.string(),
});

export const GetAssetManifestApiV1AssetManifestPathGetQueryParams = zod.object({
  id: zod.number(),
});

export const GetAssetManifestApiV1AssetManifestPathGetResponse = zod.unknown();

/**
 * @summary Register a webhook on a node
 */
export const RegisterWebhookApiV1WebhooksTargetPathPostParams = zod.object({
  path: zod.string(),
});

export const RegisterWebhookApiV1WebhooksTargetPathPostBody = zod.object({
  url: zod.string().url().min(1),
  secret: zod.union([zod.string(), zod.null()]).optional(),
  events: zod
    .union([
      zod.array(
        zod.enum([
          "container-child-created",
          "container-child-metadata-updated",
          "stream-closed",
        ]),
      ),
      zod.null(),
    ])
    .optional(),
});

export const RegisterWebhookApiV1WebhooksTargetPathPostResponse = zod.object({
  id: zod.number(),
  url: zod.string().url().min(1),
  events: zod.union([
    zod.array(
      zod.enum([
        "container-child-created",
        "container-child-metadata-updated",
        "stream-closed",
      ]),
    ),
    zod.null(),
  ]),
  active: zod.boolean(),
  time_created: zod.string().datetime({}),
});

/**
 * @summary List webhooks registered on a node
 */
export const ListWebhooksApiV1WebhooksTargetPathGetParams = zod.object({
  path: zod.string(),
});

export const ListWebhooksApiV1WebhooksTargetPathGetResponseItem = zod.object({
  id: zod.number(),
  url: zod.string().url().min(1),
  events: zod.union([
    zod.array(
      zod.enum([
        "container-child-created",
        "container-child-metadata-updated",
        "stream-closed",
      ]),
    ),
    zod.null(),
  ]),
  active: zod.boolean(),
  time_created: zod.string().datetime({}),
});
export const ListWebhooksApiV1WebhooksTargetPathGetResponse = zod.array(
  ListWebhooksApiV1WebhooksTargetPathGetResponseItem,
);

/**
 * @summary Deactivate and delete a webhook
 */
export const DeleteWebhookApiV1WebhooksWebhookIdDeleteParams = zod.object({
  webhook_id: zod.number(),
});

export const DeleteWebhookApiV1WebhooksWebhookIdDeleteResponse = zod.unknown();

/**
 * @summary Delivery history for a webhook
 */
export const WebhookHistoryApiV1WebhooksHistoryWebhookIdGetParams = zod.object({
  webhook_id: zod.number(),
});

export const webhookHistoryApiV1WebhooksHistoryWebhookIdGetQueryLimitDefault = 50;
export const webhookHistoryApiV1WebhooksHistoryWebhookIdGetQueryLimitMax = 500;

export const WebhookHistoryApiV1WebhooksHistoryWebhookIdGetQueryParams =
  zod.object({
    limit: zod
      .number()
      .min(1)
      .max(webhookHistoryApiV1WebhooksHistoryWebhookIdGetQueryLimitMax)
      .default(webhookHistoryApiV1WebhooksHistoryWebhookIdGetQueryLimitDefault),
  });

export const WebhookHistoryApiV1WebhooksHistoryWebhookIdGetResponseItem = zod
  .object({
    id: zod.number(),
    webhook_id: zod.number(),
    event_type: zod.enum([
      "container-child-created",
      "container-child-metadata-updated",
      "stream-closed",
    ]),
    payload: zod.record(zod.string(), zod.unknown()),
    status_code: zod.union([
      zod
        .union([
          zod.literal(100),
          zod.literal(101),
          zod.literal(102),
          zod.literal(103),
          zod.literal(200),
          zod.literal(201),
          zod.literal(202),
          zod.literal(203),
          zod.literal(204),
          zod.literal(205),
          zod.literal(206),
          zod.literal(207),
          zod.literal(208),
          zod.literal(226),
          zod.literal(300),
          zod.literal(301),
          zod.literal(302),
          zod.literal(303),
          zod.literal(304),
          zod.literal(305),
          zod.literal(307),
          zod.literal(308),
          zod.literal(400),
          zod.literal(401),
          zod.literal(402),
          zod.literal(403),
          zod.literal(404),
          zod.literal(405),
          zod.literal(406),
          zod.literal(407),
          zod.literal(408),
          zod.literal(409),
          zod.literal(410),
          zod.literal(411),
          zod.literal(412),
          zod.literal(413),
          zod.literal(414),
          zod.literal(415),
          zod.literal(416),
          zod.literal(417),
          zod.literal(418),
          zod.literal(421),
          zod.literal(422),
          zod.literal(423),
          zod.literal(424),
          zod.literal(425),
          zod.literal(426),
          zod.literal(428),
          zod.literal(429),
          zod.literal(431),
          zod.literal(451),
          zod.literal(500),
          zod.literal(501),
          zod.literal(502),
          zod.literal(503),
          zod.literal(504),
          zod.literal(505),
          zod.literal(506),
          zod.literal(507),
          zod.literal(508),
          zod.literal(510),
          zod.literal(511),
        ])
        .describe(
          "HTTP status codes and reason phrases\n\nStatus codes from the following RFCs are all observed:\n\n    \* RFC 7231: Hypertext Transfer Protocol (HTTP\/1.1), obsoletes 2616\n    \* RFC 6585: Additional HTTP Status Codes\n    \* RFC 3229: Delta encoding in HTTP\n    \* RFC 4918: HTTP Extensions for WebDAV, obsoletes 2518\n    \* RFC 5842: Binding Extensions to WebDAV\n    \* RFC 7238: Permanent Redirect\n    \* RFC 2295: Transparent Content Negotiation in HTTP\n    \* RFC 2774: An HTTP Extension Framework\n    \* RFC 7725: An HTTP Status Code to Report Legal Obstacles\n    \* RFC 7540: Hypertext Transfer Protocol Version 2 (HTTP\/2)\n    \* RFC 2324: Hyper Text Coffee Pot Control Protocol (HTCPCP\/1.0)\n    \* RFC 8297: An HTTP Status Code for Indicating Hints\n    \* RFC 8470: Using Early Data in HTTP",
        ),
      zod.null(),
    ]),
    attempts: zod.number(),
    outcome: zod.enum(["pending", "success", "failed"]),
    error_detail: zod.union([zod.string(), zod.null()]),
    time_created: zod.string().datetime({}),
    delivered_at: zod.union([zod.string().datetime({}), zod.null()]),
  })
  .describe("Response containing webhook delivery information.");
export const WebhookHistoryApiV1WebhooksHistoryWebhookIdGetResponse = zod.array(
  WebhookHistoryApiV1WebhooksHistoryWebhookIdGetResponseItem,
);
